# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version: '3.8'

services:
  gtfs-api:
    container_name: app
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - "${SERVER_PORT}:3000"
      - "9229:9229"
    volumes:
      - .:/app
